Repository arduino/arduino-lint, pull requests merged in 2024-10, with the labels that each got.

#764 Use Bearer/gon for macOS notarization of releases
  .github/workflows/publish-go-nightly-task.yml
  .github/workflows/release-go-task.yml
Labels: topic: infrastructure, os: macos, type: imperfection

#765 Increase markdown link check timeout to 30s
  .markdown-link-check.json
  docs/installation.md
Labels: type: enhancement, topic: infrastructure

#766 Refactor variables in release workflows
  .github/workflows/publish-go-nightly-task.yml
  .github/workflows/publish-go-tester-task.yml
  .github/workflows/release-go-task.yml
Labels: type: enhancement, topic: infrastructure

#767 Remove unused job outputs from release workflows
  .github/workflows/publish-go-nightly-task.yml
  .github/workflows/release-go-task.yml
Labels: topic: infrastructure, os: macos, type: imperfection

#768 Update redirecting URLs in reference links
  .github/dependabot.yml
  .github/workflows/check-certificates.yml
  .github/workflows/check-general-formatting-task.yml
  .github/workflows/check-go-dependencies-task.yml
  .github/workflows/check-go-task.yml
  .github/workflows/check-license.yml
  .github/workflows/check-markdown-task.yml
  .github/workflows/check-mkdocs-task.yml
  .github/workflows/check-prettier-formatting-task.yml
  .github/workflows/check-python-task.yml
  .github/workflows/check-shell-task.yml
  .github/workflows/check-workflows-task.yml
  .github/workflows/publish-go-nightly-task.yml
  .github/workflows/publish-go-tester-task.yml
  .github/workflows/spell-check-task.yml
  .github/workflows/sync-labels.yml
  .github/workflows/test-go-integration-task.yml
  .github/workflows/test-go-task.yml
  .github/workflows/test-install.yml
  .licensed.yml
Labels: topic: documentation, type: imperfection

#769 Migrate workflows from deprecated `set-output` commands
  .github/workflows/check-certificates.yml
  .github/workflows/check-code-generation-task.yml
  .github/workflows/check-go-dependencies-task.yml
  .github/workflows/check-go-task.yml
  .github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml
  .github/workflows/publish-go-tester-task.yml
  .github/workflows/sync-labels.yml
  .github/workflows/test-go-task.yml
Labels: topic: infrastructure, type: imperfection

#770 Run relevant workflows on release branch creation
  .github/workflows/check-certificates.yml
  .github/workflows/check-general-formatting-task.yml
  .github/workflows/check-license.yml
  .github/workflows/check-markdown-task.yml
  .github/workflows/check-mkdocs-task.yml
  .github/workflows/check-prettier-formatting-task.yml
  .github/workflows/check-python-task.yml
  .github/workflows/check-shell-task.yml
  .github/workflows/spell-check-task.yml
Labels: type: enhancement, topic: infrastructure

#771 Migrate workflow from deprecated `set-output` command
  .github/workflows/test-go-integration-task.yml
Labels: topic: infrastructure, type: imperfection

#772 Add schedule triggers to workflows whenever possible
  .github/workflows/check-go-task.yml
  .github/workflows/check-license.yml
  .github/workflows/check-mkdocs-task.yml
  .github/workflows/check-prettier-formatting-task.yml
  .github/workflows/check-python-task.yml
  .github/workflows/test-go-integration-task.yml
  .github/workflows/test-go-task.yml
Labels: type: enhancement, topic: infrastructure

#773 Target specific scripts in "Check Scripts" template
  .github/workflows/check-shell-task.yml
  Taskfile.yml
Labels: topic: infrastructure, type: imperfection

#774 Add support to "Check License" for checking license files in multiple paths
  .github/workflows/check-license.yml
Labels: type: enhancement, topic: infrastructure

#775 Add support to "Test Go" workflow for alternative Codecov configuration paths
  .github/workflows/test-go-task.yml
Labels: type: enhancement, topic: infrastructure

#776 Remove unnecessary line continuation escaping from workflows
  .github/workflows/check-go-task.yml
  .github/workflows/test-go-integration-task.yml
  .github/workflows/test-go-task.yml
Labels: type: enhancement, topic: infrastructure

#777 Reduce line length to <=120 in YAML files where feasible
  .github/workflows/check-shell-task.yml
  .github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml
  .github/workflows/publish-go-nightly-task.yml
  .github/workflows/release-go-task.yml
  Taskfile.yml
Labels: type: enhancement, topic: infrastructure

#779 Expand ignored path configurations
  .codespellrc
  .ecrc
  .markdownlintignore
  .prettierignore
Labels: type: enhancement, topic: infrastructure

#780 Don't run "Publish Tester Build" workflow on tag push
  .github/workflows/publish-go-tester-task.yml
Labels: topic: infrastructure, type: imperfection

#781 Add Windows path support to editorconfig-checker exclude regex
  .ecrc
Labels: topic: infrastructure, os: windows, type: imperfection

#782 Add support for non-bundled X.509 certificates to "Check Certificates" workflow
  .github/workflows/check-certificates.yml
Labels: type: enhancement, topic: infrastructure

#783 Use npm to manage Markdown tool dependencies
  .ecrc
  .github/workflows/check-markdown-task.yml
  .gitignore
  .markdownlintignore
  .prettierignore
  Taskfile.yml
  docs/CONTRIBUTING.md
  package-lock.json
  package.json
Labels: type: enhancement, topic: infrastructure

#784 Avoid platform-specific code in `markdown:check-links` task
  Taskfile.yml
Labels: type: enhancement, topic: infrastructure

#785 Use npm to manage Prettier tool dependency
  .github/workflows/check-prettier-formatting-task.yml
  Taskfile.yml
  package-lock.json
  package.json
Labels: type: enhancement, topic: infrastructure

#786 Add infrastructure to check for problems with npm configuration files
  .github/workflows/check-npm-task.yml
  README.md
  Taskfile.yml
Labels: type: enhancement, topic: infrastructure

#787 Configure Dependabot to check for outdated npm package dependencies
  .github/dependabot.yml
Labels: type: enhancement, topic: infrastructure

#790 Use engines.node as source of version data for "actions/setup-node" action
  .github/workflows/check-markdown-task.yml
  .github/workflows/check-npm-task.yml
  .github/workflows/check-prettier-formatting-task.yml
  docs/CONTRIBUTING.md
  package-lock.json
  package.json
Labels: type: enhancement, topic: infrastructure

#792 Use npm to manage "Check Workflows" tool dependencies
  .github/workflows/check-workflows-task.yml
  Taskfile.yml
  package-lock.json
  package.json
Labels: type: enhancement, topic: infrastructure

#793 Fix typos in contributor guide
  docs/CONTRIBUTING.md
Labels: topic: documentation, type: imperfection

#794 Configure script path in shell-related task calls in umbrella tasks
  Taskfile.yml
Labels: topic: infrastructure, type: imperfection

#795 Add support for dependencies preparation to `general:cache-dep-licenses` task
  Taskfile.yml
Labels: type: enhancement, topic: infrastructure

#796 Convert absolute paths used in `ci:validate` task to Windows format
  Taskfile.yml
Labels: topic: infrastructure, os: windows, type: imperfection

#797 Migrate to npm-managed GitHub label sync infrastructure
  .github/workflows/sync-labels-npm.yml
  README.md
  package-lock.json
  package.json
Labels: type: enhancement, topic: infrastructure

#798 Install standard version of Node.js in "Deploy Website" workflow
  .github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml
Labels: topic: documentation, topic: infrastructure, type: imperfection

#799 Use `pyproject.toml` as Python version source
  .gitattributes
  .github/workflows/check-mkdocs-task.yml
  .github/workflows/check-python-task.yml
  .github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml
  .github/workflows/spell-check-task.yml
  .github/workflows/test-go-integration-task.yml
  poetry.lock
  pyproject.toml
Labels: type: enhancement, topic: infrastructure

#800 Correct typo in .gitattributes comment
  .gitattributes
Labels: topic: documentation, type: imperfection

#802 Reference canonical Python version info source in contributor guide
  docs/CONTRIBUTING.md
Labels: topic: documentation, type: enhancement
